version: "3.0"

services:
    app:
        build:
            context: .
        ports:
            - "${PORT}:${PORT}"
        env_file:
          - .env
        depends_on:
          - postgres

    postgres:
        image: postgres:14
        ports:
            - "${POSTGRES_PORT}:5432"
        env_file:
          - .env
        volumes:
          - pg_data:/var/lib/postgresql/data
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pg_data: